spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
swagger-ui:
  use-root-path: true

#  spring:
#    datasource:
#      url: jdbc:h2:mem:mydb
#      username: root
#      password: root
#      driverClassName: org.h2.Driver
#    jpa:
#      hibernate:
#        ddl-auto: update
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.H2Dialect
#      show-sql: false
#    h2:
#      console:
#        enable: true
#      path: /h2
#  swagger-ui:
#    use-root-path: true

